services:
  loadbalancer-prequal:
    build: .
    container_name: lb-prequal
    ports:
      - "8080:8080"
    networks:
      - loadbalancer-net
    environment:
      - LB_ALGORITHM=prequal
      - LB_QRIF=0.84
      - LB_SELECTION_CHOICES=2
      - LB_PROBE_INTERVAL=1s
      - LB_USE_SERVER_RIF=false
      - BACKENDS=server1:80,server2:80,server3:80,server4:80,server5:80
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server5

  loadbalancer-rr:
    build: .
    container_name: lb-roundrobin
    ports:
      - "8081:8080"
    networks:
      - loadbalancer-net
    environment:
      - LB_ALGORITHM=roundrobin
      - BACKENDS=server1:80,server2:80,server3:80,server4:80,server5:80
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server5

  # Heavy antagonist
  server1:
    build: ./backend
    container_name: server1
    networks:
      - loadbalancer-net
    environment:
      - SERVER_ID=server1
      - PORT=80
      - CPU_LOAD=80
    cpus: 1.0

  # Heavy antagonist
  server2:
    build: ./backend
    container_name: server2
    networks:
      - loadbalancer-net
    environment:
      - SERVER_ID=server2
      - PORT=80
      - CPU_LOAD=80
    cpus: 1.0

  # Light antagonist
  server3:
    build: ./backend
    container_name: server3
    networks:
      - loadbalancer-net
    environment:
      - SERVER_ID=server3
      - PORT=80
      - CPU_LOAD=40
    cpus: 1.0

  # Clean
  server4:
    build: ./backend
    container_name: server4
    networks:
      - loadbalancer-net
    environment:
      - SERVER_ID=server4
      - PORT=80
      - CPU_LOAD=0
    cpus: 1.0

  # Clean
  server5:
    build: ./backend
    container_name: server5
    networks:
      - loadbalancer-net
    environment:
      - SERVER_ID=server5
      - PORT=80
      - CPU_LOAD=0
    cpus: 1.0

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - loadbalancer-net

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - loadbalancer-net
    depends_on:
      - prometheus

networks:
  loadbalancer-net:
    driver: bridge
